name: Linting
on:
  push:
    branches:
      - main
  pull_request:
    types:
      - opened
      - synchronize
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: get code
        uses: actions/checkout@v4
      - name: install poetry
        run: pipx install poetry
      - name: setup python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"
          cache: "poetry"
      - name: install deps
        run: |
          poetry env use "3.10"
          poetry install --no-interaction
      - name: Install pre-commit
        shell: bash
        run: poetry run pip install pre-commit
      - name: lint and format
        run: |
          poetry run make lint
